### ISSUE TITLE
3

### ISSUE THREAD

**Issue by jswsean** [rebeccajohnson88/PPOL564_slides_activities#22]
On question 3, is it ok if the function only allows the use the original RACE categories for `group_1` and `group_2`, as shown in the below picture (not the regrouped/derived race categories)?

![image](https://user-images.githubusercontent.com/54017275/189466285-c1bf2fdf-8298-4ea9-a5ab-902ccd855d73.png)

**Comment by rebeccajohnson88** [comment]
Yep fine for it to use the original RACE variable!
