### ISSUE TITLE
1.1 Part A

### ISSUE THREAD

**Issue by sonali-sr** [rebeccajohnson88/PPOL564_slides_activities#24]
#### Part A:

- Filter to sentences that involve incarceration (same Illinois Department of Corrections logic as in problem set two: incarceration is indicated by `COMMITMENT_TYPE` == "Illinois Department of Corrections")
- Filter out non-numeric sentence lengths (e.g., Term, Pounds, or Dollars)
- Filter to Black or White defendants

**Concepts tested and resources:** this question tests filtering rows based on logical conditions. Here are some resources:

- DataCamp on .loc: 
[https://campus.datacamp.com/courses/data-manipulation-with-pandas/slicing-and-indexing-dataframes?ex=3](https://campus.datacamp.com/courses/data-manipulation-with-pandas/slicing-and-indexing-dataframes?ex=3)

- Row subsetting section in this activity: [https://github.com/rebeccajohnson88/PPOL564_slides_activities/blob/main/activities/fall_22/solutions/01_pandas_datacleaning_solutions.ipynb](https://github.com/rebeccajohnson88/PPOL564_slides_activities/blob/main/activities/fall_22/solutions/01_pandas_datacleaning_solutions.ipynb)

**Comment by ykang888** [comment]
A quick question: for the second problem, "Filter out non-numeric sentence lengths (e.g., Term, Pounds, or Dollars)", which column do we focus on?

**Comment by shiuanC** [comment]
What is the meaning of "Filter out non-numeric sentence lengths (e.g., Term, Pounds, or Dollars)" ?
there is no column named "sentence length", which column(s) should we deal with?

**Comment by rebeccajohnson88** [comment]
> What is the meaning of "Filter out non-numeric sentence lengths (e.g., Term, Pounds, or Dollars)" ?
> 
> there is no column named "sentence length", which column(s) should we deal with?

The COMMITMENT_TERM variable has the raw length of the sentence that you can use for this filtering

**Comment by rebeccajohnson88** [comment]
@Mag-Sul you're loading the sentencing_cleaned data right? 

so you can subset to is_black_derived == True or is_white_derived == True rather than using the original messy race var


```
Use the same sentencing_cleaned data from Problem Set 2 for this assignment.
```

**Comment by sanhatahir** [comment]
![image](https://user-images.githubusercontent.com/113550291/193914075-132e50fd-0459-4a2d-836b-a65450daa33c.png)

When I use the is_black_derived == True or is_white_derived == True conditions, I'm getting these odd cases where RACE = NA, but is_black_derived is true 

Using "RACE".isin("Black","White") seems to be giving the correct dimensions for the subsequent questions

**Comment by Mag-Sul** [comment]
> @Mag-Sul you're loading the sentencing_cleaned data right?
> 
> so you can subset to is_black_derived == True or is_white_derived == True rather than using the original messy race var
> 
> ```
> Use the same sentencing_cleaned data from Problem Set 2 for this assignment.
> ```

Ahhhh yes that's it. I misread the instructions and wasn't using the cleaned dataset from the beginning. That makes a big difference - thanks!
