### ISSUE TITLE
1.1 Part B 

### ISSUE THREAD

**Issue by sonali-sr** [rebeccajohnson88/PPOL564_slides_activities#25]
### Part B: 
Then, follow the instructions in the codebook (combining `COMMITMENT_TERM` with `COMMITMENT_UNIT`) to create a standard sentence length in days column (`senlength_derived`) that measures the sentence in days. To simplify, you can assume that:

- 1 hour = 1/24th of a day
- 1 year = 365 days
- 1 month = 30.5 days
- 1 week = 7 days
- Natural life = difference between the age of 100 and the defendant's age at incident (cleaned; if missing, code to age 20); note that this is a simplification since age at incident != age at sentencing

Print the following cols for an example of each type (eg an example of originally hours; an example of natural life): `COMMITMENT_TERM`, `COMMITMENT_UNIT`, `age_derived` and your new standardized sentence length column<br>
<img width="835" alt="1 1 B part 1" src="https://user-images.githubusercontent.com/90288860/190931729-b4ad69c4-ce4a-4b7c-ab93-03bc31c629c0.PNG">

<br></br>
Print the summary of that column (`senlength_derived`) using the .describe() command<br>
<img width="570" alt="1 1 B part 2" src="https://user-images.githubusercontent.com/90288860/190931758-507b5867-9787-4089-a1f4-c3243cebda33.PNG">
<br>
**Concepts tested and resources:** there are many approaches but a couple ways are:

- np.select covered in the slides and this activity notebook: [https://github.com/rebeccajohnson88/PPOL564_slides_activities/blob/main/activities/fall_22/solutions/01_pandas_datacleaning_solutions.ipynb](https://github.com/rebeccajohnson88/PPOL564_slides_activities/blob/main/activities/fall_22/solutions/01_pandas_datacleaning_solutions.ipynb)

- writing a function that takes in one row as an argument and has a series of if, elif, else conditions where different commitment_units are translated into days. To execute this function, you can use the .apply function but apply it with axis = 1 (row-wise). Resources for that include: (1) the activity notebook on user-defined functions ([https://github.com/rebeccajohnson88/PPOL564_slides_activities/blob/main/activities/fall_22/solutions/02_functions_part1_solutions.ipynb](https://github.com/rebeccajohnson88/PPOL564_slides_activities/blob/main/activities/fall_22/solutions/02_functions_part1_solutions.ipynb)); (2) the activity notebook covering apply (same as above)

**Hint on output:** see GitHub issue for the summary stats we get from running .describe()

**Comment by xinruizhao** [comment]
![image](https://user-images.githubusercontent.com/113211059/193160182-05103814-e404-4649-b4e2-d264fb527dd0.png)
For this part, I was wondering how to print all examples in one table. I only can find a way to print them separately.

**Comment by rebeccajohnson88** [comment]
One hint is that you can group by commitment unit and then use an aggregate to print an example

**Comment by qinip** [comment]
![image](https://user-images.githubusercontent.com/5789293/193476220-73f3e1fe-2d5c-4423-b043-64a190a46e7a.png)
I got the mean and std of senlength a bit higher than the answer. Where could I have done wrong?

**Comment by sonali-sr** [comment]
Since the count value is correct, I think your initial filtering step is correct, and think there might be some small error in the way days are measured for each COMMITMENT_UNIT. You could also check if all your COMMITMENT_TERM variables are of the same type, and are being used correctly in the calculations.

**Comment by qinip** [comment]
> Since the count value is correct, I think your initial filtering step is correct, and think there might be some small error in the way days are measured for each COMMITMENT_UNIT. You could also check if all your COMMITMENT_TERM variables are of the same type, and are being used correctly in the calculations.

Thank you! You're right, I got the term "Hours" wrong by missing the "s" in my function : P

**Comment by Mag-Sul** [comment]
Finally got all my code to work, but my summary statistics are waaay off 

<img width="1121" alt="Screen Shot 2022-10-04 at 1 16 41 PM" src="https://user-images.githubusercontent.com/112567449/193884417-5fc23020-1b2f-4245-ab7e-6ecef009c563.png">

**Comment by sonali-sr** [comment]
@Mag-Sul - since your count value is wrong, I think there might be a mistake in the filtering step in 1.1.A. Make sure that all the conditions and filtering work, and if it still doesn't change - please let us know.

**Comment by Mag-Sul** [comment]
> 



> @Mag-Sul - since your count value is wrong, I think there might be a mistake in the filtering step in 1.1.A. Make sure that all the conditions and filtering work, and if it still doesn't change - please let us know.

Ah yes that's what it was - many thanks!

**Comment by bhollan** [comment]
![image](https://user-images.githubusercontent.com/8443608/194118748-34af8b2b-6e41-474b-acaf-1fbdb62aa2f9.png)
I'm getting correct stats, except for my mean and std are a bit lower (1% and 5% respectively).

**Comment by sonali-sr** [comment]
@bhollan This might be happening because you have a different condition for the Natural life assignment. By subtracting the defendant's age from 100, you will obtain the defendant's age, which is in years. You will also have to change it to days, as that is the standard we intend on attaining for the senlength_derived column,

**Comment by Madhvimm** [comment]
I am using np. where with various conditions and cases to get a new column, but when I am multiplying, the output is showing like this. what could be the issue?
![Screenshot 2022-10-06 at 2 09 58 AM](https://user-images.githubusercontent.com/114104573/194227486-14ee775d-e7fc-475c-b15f-09910af07a6b.png)

**Comment by Madhvimm** [comment]
How to deal with "COMMITMENT_TERM" == 0?
