### ISSUE TITLE
1.2 Part A 

### ISSUE THREAD

**Issue by sonali-sr** [rebeccajohnson88/PPOL564_slides_activities#26]
#### Part A

Keep the above ~58k row dataset subsetting only to sentences involving incarceration. Then, further subset the rows to:

- Those sentenced` judgeid_derived` = `judge_21`
- `simplified_offense_derived` == "Narcotics"

Use `shape` to print the dimensions of the resulting dataframe

<img width="172" alt="1 2 A" src="https://user-images.githubusercontent.com/90288860/190932019-767cb59c-dfa3-4dad-8c3e-1570fc6be50a.PNG">

**Concepts and resources:** row subsetting using logical conditions; see earlier resources

**Comment by skeyas** [comment]
I'm confused as to how these dimensions occur. The original dataframe read from the csv file only has 52 columns, and we're only asked to add one, senlength_derived. When I filter, I get the expected number of rows, but I don't see where the additional 3 columns are meant to come from.

**Comment by rebeccajohnson88** [comment]
thanks for clarifying!

only *the rows* should match our resulting .shape

the reason we have more columns is because of some intermediate columns created for the senlength_derived so as long as rows match you're good. thanks for checking!
