### ISSUE TITLE
1.2 Part B

### ISSUE THREAD

**Issue by sonali-sr** [rebeccajohnson88/PPOL564_slides_activities#27]
#### Part B
For each defendant sentenced by judge_21, you want to construct "matched groups" of defendants who:

- Are the same exact age and
- Are the same gender but
- Differ in race from the focal defendant

Write a user-defined function to find any/all matched defendants for each focal defendant of judge 21. You can structure the function in various ways but one way is to write a function similar to the class example where we find similar crimes to a focal crime for one focal crime; in this case, we want to:

- Iterate over unique defendants sentenced by judge 21 (use `CASE_PARTICIPANT_ID `to identify each unique defendant)
- Find other defendants in the judge 21 pool who (1) have a different race from that focal defendant but (2) the same gender and age

**Concepts and resources:**

- Slides and activity code on user-defined functions and iterating using list comprehension: [https://github.com/rebeccajohnson88/PPOL564_slides_activities/blob/main/activities/fall_22/solutions/02_functions_part1_solutions.ipynb](https://github.com/rebeccajohnson88/PPOL564_slides_activities/blob/main/activities/fall_22/solutions/02_functions_part1_solutions.ipynb)

- You can either write code in the function to add columns with the attributes of the focal defendant (existing material) or using pd.merge to join these on after; we'll be covering pd.merge on Wednesday 09.21 but here are some slides (slide 17-20) from my previous course in meantime: [https://github.com/rebeccajohnson88/qss20_slides_activities/blob/main/slides/s21_slides/qss20_s21_class4.pdf](https://github.com/rebeccajohnson88/qss20_slides_activities/blob/main/slides/s21_slides/qss20_s21_class4.pdf)

**Hints on output:**

- Some focal defendants may not have any matches; they can be excluded from the results
- In the way we wrote our function, each iteration of the function returns a single dataframe with the focal defendant's matched defendants

using the results from Part A, use `pd.concat` or another approach to create a dataframe that compares the (1) race and sentence length for the focal defendant to (2) the sentence length for other defendants. Using this dataframe, show this comparison for focal defendant: `CASE_PARTICIPANT_ID` == `808109112733`

<img width="869" alt="1 2 B" src="https://user-images.githubusercontent.com/90288860/190932191-36e1af48-a049-4d44-bcf0-024689966237.PNG">

**Comment by sanhatahir** [comment]
For checking, how many total rows do we get for this resultant data frame?
That is, how many rows do the 53 persons match to?

**Comment by rebeccajohnson88** [comment]
@sanhatahir it depends a bit on how you structure the resulting data (eg in some implementations each row might be a focal defendant and diff cols contain matches for diff persons; in diff implementation, each row might represent a match for a focal defendant). So I would focus on matching the above example

But in general, we found matches for 29 unique focal defendants (so the remainder didn't have matches meeting those criteria)

**Comment by jswsean** [comment]
Hi there! Just want to confirm on the matching process; is the matching mechanism conducted with replacement? 

Say there are 50 unique defendant IDs for `judge_21` (`id_1`, `id_2`, ..., etc.). 

So for `id_1`, there are 49 possible matches, right? What about for `id_2`? Would there also be 49 possible matches? Or would observations matched with `id_1` be taken from the pool?

**Comment by rebeccajohnson88** [comment]
Thanks for checking on this!

The matching should be with replacement so the same pool is available for each focal defendant (and the same other defendant might serve as match for multiple focal defendants)

**Comment by jswsean** [comment]
Also, we're told to match by the exact same age. Should we use `age_derived` or `AGE_AT_INCIDENT`?

**Comment by rebeccajohnson88** [comment]
> Also, we're told to match by the exact same age. Should we use `age_derived` or `AGE_AT_INCIDENT`?

thanks for checking! `age_derived` since we're using sentencing_cleaned and its variables throughout (tho also shouldn't make big difference)

**Comment by jswsean** [comment]
Another thing, professor -- sorry for asking again. 

Is the table that you attached above supposed to be the output of the function? Cos the way I did it so far, the output for my function is more like: 

![image](https://user-images.githubusercontent.com/54017275/192126204-0596788d-d11d-432e-9a2e-edb090d2f9b4.png)

I did the merging and the creation of the dataframes outside of the function. Is this okay?

**Comment by rebeccajohnson88** [comment]
> Another thing, professor -- sorry for asking again.
> 
> Is the table that you attached above supposed to be the output of the function? Cos the way I did it so far, the output for my function is more like:
> 
> ![image](https://user-images.githubusercontent.com/54017275/192126204-0596788d-d11d-432e-9a2e-edb090d2f9b4.png)
> 
> I did the merging and the creation of the dataframes outside of the function. Is this okay?

no problem re questions!

and yep any format is fine as long as it contains the same information which yours does
