### ISSUE TITLE
1.2 Part C

### ISSUE THREAD

**Issue by sonali-sr** [rebeccajohnson88/PPOL564_slides_activities#28]
#### Part C:
Group by the focal defendant's race and find the proportion of that defendant's matches who had a LONGER sentence than the focal defendant

**Concepts and resources**: can use groupby and agg
- Groupby and agg code: [https://github.com/rebeccajohnson88/PPOL564_slides_activities/blob/main/activities/fall_22/solutions/01_pandas_datacleaning_solutions.ipynb](https://github.com/rebeccajohnson88/PPOL564_slides_activities/blob/main/activities/fall_22/solutions/01_pandas_datacleaning_solutions.ipynb)
<img width="539" alt="1 2 C" src="https://user-images.githubusercontent.com/90288860/190932278-f0c42523-adac-45e8-b60d-e89565a773d6.PNG">

**Comment by rebeccajohnson88** [comment]
Student had good question on whether, for this we mean:

1. What % of the focal defendant from Part B's matches had a longer sentence (so the statistics only for focal defendant `808109112733` or
2. What % of all focal defendant's matches had a longer sentence

We mean interpretation 2 so:

- Include ALL focal defendants and their matches
- Group by the race of the focal defendant
- Find what % of black focal defendants had matches with a longer sentence versus what % of white focal defendants had matches with a longer sentence

Hope that helps clarify

**Comment by rebeccajohnson88** [comment]
Follow-up question:

 Is all the focal defendants means everyone can be focal defendants? And should we calculate the average proportion when different people play the role of focal defendants?

Response:

Yep so in part A and B, we give the following instruction:

`For each defendant sentenced by judge_21, you want to construct "matched groups" of defendants who:`

So the goal is to (1) iterate through each defendant, (2) treat them as the focal defendant, (3) find their matched group, and then (4) move to the next defendant, and so on (some are dropped if no matches)

So for this later question, yep it's the average proportion--- so we should have a single dataframe with all matched groups for each of the focal defendants that has information on: (1) the focal defendant's sentence length; (2) the length for those in their matched group.

You can then construct a "sentence_longer" True/False variable to get the average proportion of sentence_longer == True by race

**Comment by xinruizhao** [comment]
![image](https://user-images.githubusercontent.com/113211059/193360347-061d6fa5-a3e2-4e49-a26a-d29b80c16fb2.png)
Sorry I have a question for Part B but it's related to Part C. So right after defining the function, my code for executing the function looks like this, only for 808109112733. Then I move to Part C and realize what you want is a single dataframe with all matched groups for each defendant. So the single dataframe in Part B should be something like this part in in-class exercises?
![image](https://user-images.githubusercontent.com/113211059/193360773-e13844cc-4375-40b1-80e6-c222f3c3e8e0.png)

**Comment by rebeccajohnson88** [comment]
> ![image](https://user-images.githubusercontent.com/113211059/193360347-061d6fa5-a3e2-4e49-a26a-d29b80c16fb2.png) Sorry I have a question for Part B but it's related to Part C. So right after defining the function, my code for executing the function looks like this, only for 808109112733. Then I move to Part C and realize what you want is a single dataframe with all matched groups for each defendant. So the single dataframe in Part B should be something like this part in in-class exercises? ![image](https://user-images.githubusercontent.com/113211059/193360773-e13844cc-4375-40b1-80e6-c222f3c3e8e0.png)

thanks for checking on this and sorry for slow response!

yep that in-class example is very close to what you should do for this problem. In particular, you can do something like:

```
all_matches = [match_defendant(one_id) for one_id in df.focal_defendant_id.unique()]
```

one thing you may want to add to the function is adding the focal defendant's id and sentence length as new columns so that you can easily create a new variable that returns True if one of the sentence lengths is longer
