### ISSUE TITLE
2 - Optional extra credit

### ISSUE THREAD

**Issue by sonali-sr** [rebeccajohnson88/PPOL564_slides_activities#30]
### Optional extra credit/challenge exercise (1 point): Impute possible judge demographic correlates of sentencing

The previous exercises showed large differences in sentences between judges/differences in disparities. You become interested in how the judge's own demographic attributes are correlated with sentencing. Going back to the judge's name (`SENTENCE JUDGE`), parse their first name and try to probabilistically infer his or her gender. Then, investigate whether disparities differ between "likely female" and "likely male" judges.

**Note on ethics of probabilistic inference of attributes based on name:** Using names to infer demographic characteristics has become increasingly popular with the rise of "digital trace data" that often lacks explicit demographic fields (e.g., tweets just have usernames and profiles; academic citation networks just have author names; voter registration records sometimes just have names and not race/ethnicity). But there are many valid ethical critiques of this practice. In the case of gender, a person's assigned name at birth clearly does not always map onto their self-identified gender, both due to gender fluidity and names like "Morgan." A couple critiques I link to are:

[This blog post](https://scatter.wordpress.com/2021/07/30/who-writes-social-science/)
[Urban Institute ethical risks of race/ethnicity imputation - applies to gender](https://www.urban.org/research/publication/five-ethical-risks-consider-filling-missing-race-and-ethnicity-data)

**Comment by rebeccajohnson88** [comment]
yep fine to use an external library; you may want to look into some of the results to see how well it's working based on your manual reading of a few cases classified as each type; depending on the library, you can also augment the dictionary they use

**Comment by jswsean** [comment]
Should we focus on narcs offenses for this problem too? And the same characteristics (age, gender and race) to match on?

**Comment by rebeccajohnson88** [comment]
> Should we focus on narcs offenses for this problem too? And the same characteristics (age, gender and race) to match on?

totally up to you on that! main focus of this is different ways to impute judge demographics based on name and cleaning/parsing of names to do so
