### ISSUE TITLE
3 - Optional Extra Credit

### ISSUE THREAD

**Issue by sonali-sr** [rebeccajohnson88/PPOL564_slides_activities#31]
### 3. Optional extra credit/challenge exercise (1 point): examine disparities across multiple judges

In problem 1.2, we focused on one judge: judge 21

For this extra credit exercise:

- Get judges with a sufficient sample size: filter to each judge with at least 20 Black and at least 20 white defendants

- Calculate the within-judge disparity and plot the (1) median sentence length for Black defendants and (2) median sentence length for white defendants (factor variable on x axis for each judge_id who qualifies; group by race)

- Write a 1-2 sentence interpretation - if we assume that cases/defendants are randomly assigned to sentencing judges, what might this suggest about the role of judicial discretion in these disparities?

**Comment by brad-gt** [comment]
I'm not sure I understand what you want in the plot, could we get an example output for this one?
