### ISSUE TITLE
2.4 - Part B 

### ISSUE THREAD

**Issue by sonali-sr** [rebeccajohnson88/PPOL564_slides_activities#43]
### 2.4 More joins and more cleaning (5 points)

B. Create a new column in `debar_clean` called `name_clean_2 `that uses regex to take the following name in that dataset:

- `SLASH E.V. RANCH LLP` in the `debar_clean` dataset

And cleans it up so that it matches with this employer in `jobs`

- `SLASH EV RANCH` in the `jobs` dataset

Eg a pattern to remove the dots in the EV and the space+LLP-- you can apply the pattern to all employer names in debar_clean (so don't need to worry about only applying it to that one employer)

<img width="673" alt="2 4 b" src="https://user-images.githubusercontent.com/90288860/194927182-22866ecd-dc20-4a9f-b0a8-3249629d71ef.PNG">

**Comment by xinruizhao** [comment]
Hi, for a quick clarification, are we removing LLP in the ones after EV or are we removing all LLP in debar_clean?
Thanks in advance!

**Comment by rebeccajohnson88** [comment]
> Hi, for a quick clarification, are we removing LLP in the ones after EV or are we removing all LLP in debar_clean? Thanks in advance!

just fixing the SLASH EV RANCH one - thanks!
