### ISSUE TITLE
3 - C, D and E

### ISSUE THREAD

**Issue by sonali-sr** [rebeccajohnson88/PPOL564_slides_activities#61]
### 3. Extend the analysis from unigrams to bigrams (9 points)

**C.** Use the `create_dtm` function and the `processed_text_bigrams` column to create a document-term matrix (`dtm_bigram`) with these bigrams. Keep the following three columns in the data: `id`, `topics_clean`, and `compound`

**D.** Print the (1) dimensions of the `dtm` matrix from question 2.2 and (2) the dimensions of the `dtm_bigram` matrix. Comment on why the bigram matrix has more dimensions than the unigram matrix. 

<img width="273" alt="3D" src="https://user-images.githubusercontent.com/90288860/197819775-f7eeb2a2-bcd6-44a9-bba1-3f87d0a3a5cd.PNG">

**E.** Find and print the 10 most prevelant bigrams for each of the three topics_clean using the `get_topwords` function from 2.2

<img width="209" alt="3E" src="https://user-images.githubusercontent.com/90288860/197819941-67362c85-7f85-494c-bd03-a529919632b9.PNG">

**Comment by JiaqinWu** [comment]
![image](https://user-images.githubusercontent.com/112026682/197909901-22164ed9-9b53-407f-8494-83c305fdddfa.png)
Hi professor! A little bit of difference in the number of rows of my dataframe. Does it matter? Thanks!

**Comment by rebeccajohnson88** [comment]
> ![image](https://user-images.githubusercontent.com/112026682/197909901-22164ed9-9b53-407f-8494-83c305fdddfa.png) Hi professor! A little bit of difference in the number of rows of my dataframe. Does it matter? Thanks!

nope that's fine and relates to differences in preprocessing (number of rows should stay 717 but # cols can vary)
