### ISSUE TITLE
2.5 group by year 

### ISSUE THREAD

**Issue by sonali-sr** [rebeccajohnson88/PPOL564_slides_activities#76]
### 2.5 group by year and find the percentage of states where male scores are higher than females (4 points)

**A.** Write a query that (1) groups by year and (2) finds the percentage of states for that year where males have higher scores than females

**B.** Interpret the results

_**Hint:**_ can either use subquery to construct the `is_male_higher` and use it or do it all in one query with a comparison; the `avg `command is useful

Head of dataframe : 

<img width="187" alt="2 5 year" src="https://user-images.githubusercontent.com/90288860/200561820-b02f4ebe-1009-4189-b878-24f36d42753b.PNG">

**Comment by Chuyuan-Zhong** [comment]
Hi Professor, when I try to print the table, it includes the is_male_higher column, then for the next outputs, there are two is_male_higher columns and their means, for the next next question, there is an error saying column reference "is_male_higher" is ambiguous. It worked fine before, but now I think the is_male_higher column is included in the original table. 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/82311601/203156214-f26d1766-6828-4789-9e37-c894a5e34833.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/82311601/203156309-90f22304-efc6-4cc3-b8a2-408477f79d07.png">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/82311601/203156940-a2a62e95-3f6e-4fdd-99c5-49d7b49b6286.png">

**Comment by rebeccajohnson88** [comment]
> Hi Professor, when I try to print the table, it includes the is_male_higher column, then for the next outputs, there are two is_male_higher columns and their means, for the next next question, there is an error saying column reference "is_male_higher" is ambiguous. It worked fine before, but now I think the is_male_higher column is included in the original table. <img alt="image" width="791" src="https://user-images.githubusercontent.com/82311601/203156214-f26d1766-6828-4789-9e37-c894a5e34833.png"> <img alt="image" width="448" src="https://user-images.githubusercontent.com/82311601/203156309-90f22304-efc6-4cc3-b8a2-408477f79d07.png"> <img alt="image" width="704" src="https://user-images.githubusercontent.com/82311601/203156940-a2a62e95-3f6e-4fdd-99c5-49d7b49b6286.png">

yep the issue here is that is_male_higher seems to exist in both tmp and math_gencompare - i'd explicitly alias which table you're using it from (eg tmp.is_male_higher)
